### ISSUE TITLE
params.clear overrides params.cookies (deletes cookies)

### ISSUE THREAD

**Issue by omrilotan** [sitespeedio/browsertime-extension#12]
### Expected behaviour
When `clear` param is set to `true` and `cookies` options contains values, the cookie should remain (clean the cache first)

### Current behaviour
Cache clear runs after cookie set, removing all cookies.

### Suggestion
Re arrange the order, and extract the cookie set from Promise array (to prevent race condition)

Taking over issue in sitespeed.io repo: https://github.com/sitespeedio/sitespeed.io/issues/2185

**Comment by soulgalore** [comment]
Thank you @omrilotan feel free to have a go if you want, else I will start looking tonight.

Best
Peter

**Comment by omrilotan** [comment]
Addressed in https://github.com/sitespeedio/browsertime-extension/pull/13
