### ISSUE TITLE
RequestHeaders are not modified for websocket

### ISSUE THREAD

**Issue by markuswall** [sitespeedio/browsertime-extension#5]
When a header is added, it is attached to http[s] requests, but not requests to open a websocket. I have a scenario where I need to pass a custom header with the websocket, thus it would be great if this extension could do that by default.

By adding `"wss://*/*"` to the permissions in manifest.json, it seems to work as expected in Chrome.

**Comment by tobli** [comment]
Awesome! Could you please submit a PR?

**Comment by soulgalore** [comment]
@markuswall I've pushed this to master of Browsertime, can you help us test there that it works for you? Then please let us know if you use Browsertime or sitespeed.io and we can do a fix release.

**Comment by markuswall** [comment]
I'll have a look during the day. I'm usually using sitespeed.io.

**Comment by soulgalore** [comment]
Cool, I'll fix a release during the day then.

**Comment by markuswall** [comment]
Change tested on the Browsertime 2.x branch. Works as intended on both Chrome and Firefox. I've just tested my specific scenario, but the risk should be extremely low that something else would break.

**Comment by soulgalore** [comment]
This was released a long time ago :)
